# Generated by Django 2.1.7 on 2019-04-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianmei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseimage',
            name='image',
            field=models.ImageField(null=True, upload_to='case_image', verbose_name='案例图片'),
        ),
        migrations.AlterField(
            model_name='designer',
            name='portrait',
            field=models.ImageField(upload_to='designer', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='houseproject',
            name='image',
            field=models.ImageField(null=True, upload_to='house_project', verbose_name='楼盘图片'),
        ),
    ]
