# Generated by Django 2.1.7 on 2019-04-22 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jianmei', '0002_auto_20190421_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseTypeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='house_type_image', verbose_name='户型图')),
            ],
            options={
                'verbose_name': '户型图',
                'verbose_name_plural': '户型图',
            },
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': '楼盘案例', 'verbose_name_plural': '楼盘案例'},
        ),
        migrations.AlterModelOptions(
            name='caseimage',
            options={'verbose_name': '案例图片', 'verbose_name_plural': '案例图片'},
        ),
        migrations.AlterModelOptions(
            name='designer',
            options={'verbose_name': '设计师', 'verbose_name_plural': '设计师'},
        ),
        migrations.AlterModelOptions(
            name='housetype',
            options={'verbose_name': '户型', 'verbose_name_plural': '户型'},
        ),
        migrations.AddField(
            model_name='housetypeimage',
            name='house_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianmei.HouseType', verbose_name='所属户型'),
        ),
    ]
