# Generated by Django 2.1.7 on 2019-04-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianmei', '0003_auto_20190422_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='show_index',
            field=models.IntegerField(null=True, verbose_name='首页显示顺序'),
        ),
        migrations.AddField(
            model_name='caseimage',
            name='is_show_on_index',
            field=models.BooleanField(default=False, verbose_name='是否在首页展示（仅一张图片）'),
        ),
    ]
