# Generated by Django 2.1.7 on 2019-05-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianmei', '0005_auto_20190505_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='正文图片'),
        ),
        migrations.AlterField(
            model_name='article',
            name='click_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='点击次数'),
        ),
        migrations.AlterField(
            model_name='designer',
            name='desc',
            field=models.CharField(blank=True, max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='houseproject',
            name='designers',
            field=models.ManyToManyField(blank=True, to='jianmei.Designer', verbose_name='所属设计师'),
        ),
    ]
