# Generated by Django 2.1.7 on 2019-05-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianmei', '0006_auto_20190508_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='show_on_index',
            field=models.BooleanField(default=False, verbose_name='是否在首页展示'),
        ),
    ]
