# Generated by Django 2.1.7 on 2019-05-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianmei', '0007_designer_show_on_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(default='装修百科', max_length=50, verbose_name='类别'),
        ),
    ]
