# Generated by Django 2.1.7 on 2019-05-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jianmei', '0009_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='reply',
            new_name='replied',
        ),
    ]
