# Generated by Django 2.1.7 on 2019-05-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianmei', '0010_auto_20190519_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseproject',
            name='consult_count',
        ),
        migrations.RemoveField(
            model_name='houseproject',
            name='started_count',
        ),
        migrations.RemoveField(
            model_name='housetype',
            name='style',
        ),
        migrations.AddField(
            model_name='case',
            name='style',
            field=models.CharField(default='', max_length=20, verbose_name='装修风格'),
        ),
        migrations.AlterField(
            model_name='houseproject',
            name='finished_count',
            field=models.IntegerField(default=0, verbose_name='施工户数'),
        ),
    ]
