# Generated by Django 2.1.7 on 2019-06-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianmei', '0012_auto_20190605_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='logo')),
            ],
            options={
                'verbose_name': '首页大幅海报',
                'verbose_name_plural': '首页大幅海报',
            },
        ),
    ]
