# Generated by Django 2.1.7 on 2019-07-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jianmei', '0013_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseproject',
            name='designers',
        ),
        migrations.AddField(
            model_name='case',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jianmei.Designer', verbose_name='所属设计师'),
        ),
    ]
